import "./components/header-fix.js"
import "./components/hero-bg-animation.js"
import "./components/services-swiper.js"
import "./components/spoiler.js"
import "./components/companies-sliders.js"
import "./components/form-submit-checkbox.js"
import "./components/burger.js"
